services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=anshul
      - POSTGRES_DB=database
      - POSTGRES_PASSWORD=anshul
    ports:
      - 5435:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  backend-1:
    image: anshul8394/cr45-backend:latest
    build: ./backend
    environment:
      - DATABASE_URL=postgres://anshul:anshul@db:5432/database?sslmode=disable
      - HTTP_ADDR=:8080
    depends_on:
      - db
    restart: unless-stopped

  backend-2:
    image: anshul8394/cr45-backend:latest
    build: ./backend
    environment:
      - DATABASE_URL=postgres://anshul:anshul@db:5432/database?sslmode=disable
      - HTTP_ADDR=:8080
    depends_on:
      - db
    restart: unless-stopped

  backend-3:
    image: anshul8394/cr45-backend:latest
    build: ./backend
    environment:
      - DATABASE_URL=postgres://anshul:anshul@db:5432/database?sslmode=disable
      - HTTP_ADDR=:8080
    depends_on:
      - db
    restart: unless-stopped

  backend-4:
    image: anshul8394/cr45-backend:latest
    build: ./backend
    environment:
      - DATABASE_URL=postgres://anshul:anshul@db:5432/database?sslmode=disable
      - HTTP_ADDR=:8080
    depends_on:
      - db
    restart: unless-stopped

  backend-5:
    image: anshul8394/cr45-backend:latest
    build: ./backend
    environment:
      - DATABASE_URL=postgres://anshul:anshul@db:5432/database?sslmode=disable
      - HTTP_ADDR=:8080
    depends_on:
      - db
    restart: unless-stopped

  # frontend:
  #   build: "./frontend"
  #   ports:
  #     - 3000:80
  #   restart: on-failure

  nginx:
    image: anshul8394/cr45-nginx:latest
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - backend-1
      - backend-2
      - backend-3
      - backend-4
      - backend-5
    restart: unless-stopped

  jenkins:
    build: ./jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: on-failure

volumes:
  pgdata:
  jenkins_home:
